# Generated by Django 3.2.18 on 2023-02-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdirectory',
            name='facebook',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orgdirectory',
            name='instagram',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orgdirectory',
            name='website',
            field=models.CharField(default='gjdjdj', max_length=254),
            preserve_default=False,
        ),
    ]
