# Generated by Django 3.2.18 on 2023-02-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='image',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
